name: ms_single_multi_select_dropdown
description: "A customizable Flutter widget for single and multi-select dropdowns dialog with search, styling, and focus control. Ideal for forms, filters, and dynamic lists."
version: 0.0.1
homepage: https://github.com/madeehasoft/ms_single_multi_select_dropdown.git
repository: https://github.com/madeehasoft/ms_single_multi_select_dropdown.git

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android: 
    minSdkVersion: 21
  ios: 
    minSdkVersion: 9.0
  web:
    renderer: html  
  macos:
    minSdkVersion: 10.11

linter:
  rules:
    - public_member_api_docs
    
topics: 
  - multi-select
  - single-select
  - dropdown
  - selector
  - list-item-finder
  - clear-all
  - done-button
  - sellected-item-view
  
license: MIT


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
 assets:
     - images/11.png
     - images/11.png
     - images/33.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package